const { pool } = require('./src/db');

async function setupShifts() {
  const client = await pool.connect();
  try {
    console.log("Creating shifts table...");
    await client.query(`
      CREATE TABLE IF NOT EXISTS shifts (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          shift_name TEXT NOT NULL UNIQUE,
          start_time TIME NOT NULL,
          end_time TIME NOT NULL,
          color TEXT NOT NULL DEFAULT '#3b82f6',
          bg TEXT NOT NULL DEFAULT '#eff6ff',
          icon TEXT NOT NULL DEFAULT 'fas fa-clock',
          description TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    console.log("Inserting default shifts...");
    await client.query(`
      INSERT INTO shifts (shift_name, start_time, end_time, color, bg, icon, description)
      VALUES 
        ('General Shift', '09:00:00', '18:00:00', '#3b82f6', '#eff6ff', 'fas fa-sun', 'Standard office hours for most internal employees.'),
        ('Field Shift', '10:00:00', '19:00:00', '#f59e0b', '#fffbeb', 'fas fa-map-marked-alt', 'Staggered hours for field agents and on-site technicians.')
      ON CONFLICT (shift_name) DO NOTHING;
    `);

    console.log("Updating employees table to include shift_id...");
    await client.query(`
      ALTER TABLE employees ADD COLUMN IF NOT EXISTS shift_id BIGINT;
    `);

    console.log("Migrating existing shift_type to shift_id...");
    const genShift = await client.query("SELECT id FROM shifts WHERE shift_name = 'General Shift'");
    const fieldShift = await client.query("SELECT id FROM shifts WHERE shift_name = 'Field Shift'");
    
    if (genShift.rows.length > 0) {
      await client.query("UPDATE employees SET shift_id = $1 WHERE shift_type = 'General' OR shift_type = 'General Shift' OR shift_id IS NULL", [genShift.rows[0].id]);
    }
    if (fieldShift.rows.length > 0) {
      await client.query("UPDATE employees SET shift_id = $1 WHERE shift_type = 'Field' OR shift_type = 'Field Shift'", [fieldShift.rows[0].id]);
    }

    console.log("Shifts setup completed successfully!");
  } catch (err) {
    console.error("Error setting up shifts:", err);
  } finally {
    client.release();
    process.exit(0);
  }
}

setupShifts();
