const { pool } = require('./db');

async function setupServiceDatabase() {
  const client = await pool.connect();
  try {
    console.log("Creating Service & AMC tables...");

    // 1. Service Requests
    await client.query(`
      CREATE TABLE IF NOT EXISTS service_requests (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          request_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          customer TEXT,
          issue TEXT,
          status TEXT NOT NULL DEFAULT 'Open',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 2. Service Calls
    await client.query(`
      CREATE TABLE IF NOT EXISTS service_calls (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          call_no TEXT NOT NULL UNIQUE,
          request_id BIGINT,
          priority TEXT,
          status TEXT NOT NULL DEFAULT 'Scheduled',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 3. Technician Assignments
    await client.query(`
      CREATE TABLE IF NOT EXISTS service_technician_assignments (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          assignment_no TEXT NOT NULL UNIQUE,
          call_id BIGINT,
          technician TEXT,
          scheduled_date DATE,
          status TEXT NOT NULL DEFAULT 'Assigned',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 4. Preventive Maintenance
    await client.query(`
      CREATE TABLE IF NOT EXISTS service_preventive_maintenance (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          pm_no TEXT NOT NULL UNIQUE,
          equipment TEXT,
          schedule_date DATE,
          status TEXT NOT NULL DEFAULT 'Scheduled',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 5. AMC
    await client.query(`
      CREATE TABLE IF NOT EXISTS service_amc (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          amc_no TEXT NOT NULL UNIQUE,
          customer TEXT,
          start_date DATE,
          end_date DATE,
          amount NUMERIC(15,2),
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 6. Breakdown / Complaint
    await client.query(`
      CREATE TABLE IF NOT EXISTS service_breakdown (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          breakdown_no TEXT NOT NULL UNIQUE,
          equipment TEXT,
          reported_date DATE,
          severity TEXT,
          status TEXT NOT NULL DEFAULT 'Open',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 7. Service Closures
    await client.query(`
      CREATE TABLE IF NOT EXISTS service_closures (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          closure_no TEXT NOT NULL UNIQUE,
          call_id BIGINT,
          completion_date DATE,
          resolution TEXT,
          status TEXT NOT NULL DEFAULT 'Closed',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    console.log("Service & AMC tables created successfully.");
  } catch (error) {
    console.error("Error creating Service & AMC tables:", error);
  } finally {
    client.release();
  }
}

setupServiceDatabase();
