const { pool } = require('./db');

async function setupProjectsDatabase() {
  const client = await pool.connect();
  try {
    console.log("Creating Projects & Installation tables...");

    // 1. Project Master
    await client.query(`
      CREATE TABLE IF NOT EXISTS project_master (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          project_code TEXT NOT NULL UNIQUE,
          name TEXT NOT NULL,
          customer_id BIGINT,
          type TEXT NOT NULL DEFAULT '',
          start_date DATE,
          end_date DATE,
          status TEXT NOT NULL DEFAULT 'In Progress',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 2. Project Tasks
    await client.query(`
      CREATE TABLE IF NOT EXISTS project_tasks (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          task_id TEXT NOT NULL UNIQUE,
          project_id BIGINT,
          name TEXT NOT NULL,
          assigned_to TEXT NOT NULL DEFAULT '',
          start_date DATE,
          due_date DATE,
          status TEXT NOT NULL DEFAULT 'Pending',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 3. Project BOQ
    await client.query(`
      CREATE TABLE IF NOT EXISTS project_boq (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          boq_code TEXT NOT NULL UNIQUE,
          project_id BIGINT,
          total_items INTEGER NOT NULL DEFAULT 0,
          total_value NUMERIC(15,2) NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Draft',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 4. Project Resources
    await client.query(`
      CREATE TABLE IF NOT EXISTS project_resources (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          resource_name TEXT NOT NULL,
          type TEXT NOT NULL DEFAULT '',
          skills TEXT NOT NULL DEFAULT '',
          assigned_project BIGINT,
          from_date DATE,
          to_date DATE,
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 5. Project Milestones
    await client.query(`
      CREATE TABLE IF NOT EXISTS project_milestones (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          milestone_name TEXT NOT NULL,
          project_id BIGINT,
          planned_date DATE,
          actual_date DATE,
          status TEXT NOT NULL DEFAULT 'Pending',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 6. Project Site Reports
    await client.query(`
      CREATE TABLE IF NOT EXISTS project_site_reports (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          report_id TEXT NOT NULL UNIQUE,
          project_id BIGINT,
          site_location TEXT NOT NULL DEFAULT '',
          date DATE,
          report_type TEXT NOT NULL DEFAULT '',
          submitted_by TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Submitted',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 7. Project Documents
    await client.query(`
      CREATE TABLE IF NOT EXISTS project_documents (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          file_name TEXT NOT NULL,
          project_id BIGINT,
          document_type TEXT NOT NULL DEFAULT '',
          upload_date DATE,
          uploaded_by TEXT NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    console.log("Projects & Installation tables created successfully!");
  } catch (error) {
    console.error("Error setting up projects database:", error);
  } finally {
    client.release();
  }
}

setupProjectsDatabase()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
