const { pool } = require('./db');

async function setupInventoryDatabase() {
  const client = await pool.connect();
  try {
    console.log("Creating Inventory & Logistics tables...");

    // 1. Warehouses
    await client.query(`
      CREATE TABLE IF NOT EXISTS inventory_warehouses (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          warehouse_name TEXT NOT NULL,
          type TEXT NOT NULL,
          location TEXT,
          capacity INTEGER,
          utilization INTEGER,
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 2. Stock Ledger
    await client.query(`
      CREATE TABLE IF NOT EXISTS inventory_stock_ledger (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          date DATE NOT NULL,
          item_code TEXT NOT NULL,
          item_name TEXT,
          voucher_type TEXT,
          qty INTEGER NOT NULL DEFAULT 0,
          balance INTEGER NOT NULL DEFAULT 0,
          warehouse_id BIGINT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 3. Material Receipt
    await client.query(`
      CREATE TABLE IF NOT EXISTS inventory_material_receipt (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          receipt_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          supplier TEXT,
          reference_po TEXT,
          items INTEGER NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Received',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 4. Material Issue
    await client.query(`
      CREATE TABLE IF NOT EXISTS inventory_material_issue (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          issue_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          project_dept TEXT,
          items INTEGER NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Issued',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 5. Stock Transfer
    await client.query(`
      CREATE TABLE IF NOT EXISTS inventory_stock_transfer (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          transfer_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          from_warehouse TEXT,
          to_warehouse TEXT,
          items INTEGER NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Completed',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 6. Stock Reconciliation
    await client.query(`
      CREATE TABLE IF NOT EXISTS inventory_stock_reconciliation (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          reconciliation_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          warehouse TEXT,
          items_count INTEGER NOT NULL DEFAULT 0,
          variance NUMERIC(5,2),
          status TEXT NOT NULL DEFAULT 'Completed',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 7. Delivery
    await client.query(`
      CREATE TABLE IF NOT EXISTS inventory_delivery (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          delivery_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          customer TEXT,
          sales_order TEXT,
          items INTEGER NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Dispatched',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 8. Returns
    await client.query(`
      CREATE TABLE IF NOT EXISTS inventory_returns (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          return_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          type TEXT,
          reference TEXT,
          items INTEGER NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Received',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    console.log("Inventory tables created successfully.");
  } catch (error) {
    console.error("Error creating Inventory tables:", error);
  } finally {
    client.release();
  }
}

setupInventoryDatabase();
