const { pool } = require('./db');

async function setupMISDatabase() {
  const client = await pool.connect();
  try {
    console.log("Creating MIS tables...");

    // 1. Reports
    await client.query(`
      CREATE TABLE IF NOT EXISTS mis_reports (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          report_name TEXT NOT NULL UNIQUE,
          description TEXT,
          last_generated DATE,
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 2. Budgets
    await client.query(`
      CREATE TABLE IF NOT EXISTS mis_budgets (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          financial_year TEXT NOT NULL,
          company TEXT,
          sales_budget DECIMAL,
          purchase_budget DECIMAL,
          operating_expense DECIMAL,
          project_expense DECIMAL,
          service_expense DECIMAL,
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 3. KPIs
    await client.query(`
      CREATE TABLE IF NOT EXISTS mis_kpi (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          metric TEXT NOT NULL UNIQUE,
          target TEXT,
          actual TEXT,
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 4. Reviews
    await client.query(`
      CREATE TABLE IF NOT EXISTS mis_reviews (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          review_type TEXT NOT NULL UNIQUE,
          period TEXT,
          notes TEXT,
          status TEXT NOT NULL DEFAULT 'Scheduled',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    console.log("MIS tables created successfully.");
  } catch (error) {
    console.error("Error creating MIS tables:", error);
  } finally {
    client.release();
  }
}

setupMISDatabase();
