const { pool } = require('./db');

async function setupAssetsDatabase() {
  const client = await pool.connect();
  try {
    console.log("Creating Assets & Installed Base tables...");

    // 1. Asset Registry
    await client.query(`
      CREATE TABLE IF NOT EXISTS assets_registry (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          asset_no TEXT NOT NULL UNIQUE,
          product TEXT,
          serial_no TEXT,
          customer TEXT,
          location TEXT,
          installation_date DATE,
          warranty_expiry DATE,
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 2. Warranty & AMC
    await client.query(`
      CREATE TABLE IF NOT EXISTS assets_warranty_amc (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          amc_no TEXT NOT NULL UNIQUE,
          asset_id BIGINT,
          customer TEXT,
          start_date DATE,
          end_date DATE,
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 3. Service History
    await client.query(`
      CREATE TABLE IF NOT EXISTS assets_service_history (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          ticket_no TEXT NOT NULL UNIQUE,
          asset_id BIGINT,
          service_type TEXT,
          service_date DATE,
          engineer TEXT,
          status TEXT NOT NULL DEFAULT 'Completed',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 4. Locations
    await client.query(`
      CREATE TABLE IF NOT EXISTS assets_locations (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          location_name TEXT NOT NULL UNIQUE,
          type TEXT,
          asset_count INTEGER DEFAULT 0,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    console.log("Assets tables created successfully.");
  } catch (error) {
    console.error("Error creating Assets tables:", error);
  } finally {
    client.release();
  }
}

setupAssetsDatabase();
