const { pool } = require('./db');

async function setupDatabase() {
  const client = await pool.connect();
  try {
    console.log("Creating tables...");
    
    // 0. Session Table (for connect-pg-simple)
    await client.query(`
      CREATE TABLE IF NOT EXISTS "session" (
        "sid" varchar NOT NULL COLLATE "default",
        "sess" json NOT NULL,
        "expire" timestamp(6) NOT NULL,
        PRIMARY KEY ("sid") NOT DEFERRABLE INITIALLY IMMEDIATE
      ) WITH (OIDS=FALSE);
    `);
    await client.query(`
      CREATE INDEX IF NOT EXISTS "IDX_session_expire" ON "session" ("expire");
    `);

    // 1. Records
    await client.query(`
      CREATE TABLE IF NOT EXISTS records (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          module_id TEXT NOT NULL,
          entity TEXT NOT NULL,
          title TEXT NOT NULL,
          status TEXT NOT NULL DEFAULT 'Open',
          notes TEXT NOT NULL DEFAULT '',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          owner_id BIGINT,
          pipeline_id TEXT,
          source_id BIGINT,
          function_id TEXT
      )
    `);

    // 2. Users
    await client.query(`
      CREATE TABLE IF NOT EXISTS users (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          username TEXT NOT NULL UNIQUE,
          full_name TEXT NOT NULL,
          role_id TEXT NOT NULL,
          password_hash TEXT NOT NULL,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          must_change_password INTEGER NOT NULL DEFAULT 0,
          is_active INTEGER NOT NULL DEFAULT 1
      )
    `);

    // 3. User Permissions
    await client.query(`
      CREATE TABLE IF NOT EXISTS user_permissions (
          user_id BIGINT NOT NULL,
          module_id TEXT NOT NULL,
          function_id TEXT NOT NULL,
          can_read INTEGER NOT NULL DEFAULT 0,
          can_write INTEGER NOT NULL DEFAULT 0,
          can_create INTEGER NOT NULL DEFAULT 0,
          can_submit INTEGER NOT NULL DEFAULT 0,
          can_cancel INTEGER NOT NULL DEFAULT 0,
          can_amend INTEGER NOT NULL DEFAULT 0,
          can_print INTEGER NOT NULL DEFAULT 0,
          can_email INTEGER NOT NULL DEFAULT 0,
          can_export INTEGER NOT NULL DEFAULT 0,
          can_report INTEGER NOT NULL DEFAULT 0,
          can_share INTEGER NOT NULL DEFAULT 0,
          can_delete INTEGER NOT NULL DEFAULT 0,
          can_import INTEGER NOT NULL DEFAULT 0,
          PRIMARY KEY (user_id, module_id, function_id)
      )
    `);

    // 4. Companies
    await client.query(`
      CREATE TABLE IF NOT EXISTS companies (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          company_name TEXT NOT NULL,
          company_code TEXT NOT NULL UNIQUE,
          legal_name TEXT NOT NULL DEFAULT '',
          company_type TEXT NOT NULL DEFAULT 'Private Limited',
          status TEXT NOT NULL DEFAULT 'Active',
          parent_company TEXT NOT NULL DEFAULT '',
          website TEXT NOT NULL DEFAULT '',
          pan TEXT NOT NULL DEFAULT '',
          gst_registration_status TEXT NOT NULL DEFAULT 'Registered',
          gstin TEXT NOT NULL DEFAULT '',
          gst_state TEXT NOT NULL DEFAULT '',
          cin TEXT NOT NULL DEFAULT '',
          tan TEXT NOT NULL DEFAULT '',
          registration_number TEXT NOT NULL DEFAULT '',
          registration_date TEXT NOT NULL DEFAULT '',
          address_line1 TEXT NOT NULL DEFAULT '',
          address_line2 TEXT NOT NULL DEFAULT '',
          city TEXT NOT NULL DEFAULT '',
          state TEXT NOT NULL DEFAULT '',
          country TEXT NOT NULL DEFAULT 'India',
          pincode TEXT NOT NULL DEFAULT '',
          phone TEXT NOT NULL DEFAULT '',
          email TEXT NOT NULL DEFAULT '',
          default_currency TEXT NOT NULL DEFAULT 'INR',
          fiscal_year TEXT NOT NULL DEFAULT '',
          default_branch TEXT NOT NULL DEFAULT '',
          default_warehouse TEXT NOT NULL DEFAULT '',
          default_price_list TEXT NOT NULL DEFAULT '',
          mod_presales INTEGER NOT NULL DEFAULT 1,
          mod_sales INTEGER NOT NULL DEFAULT 1,
          mod_purchase INTEGER NOT NULL DEFAULT 1,
          mod_projects INTEGER NOT NULL DEFAULT 1,
          mod_inventory INTEGER NOT NULL DEFAULT 1,
          mod_logistics INTEGER NOT NULL DEFAULT 1,
          mod_service INTEGER NOT NULL DEFAULT 1,
          mod_amc INTEGER NOT NULL DEFAULT 1,
          mod_assets INTEGER NOT NULL DEFAULT 1,
          primary_contact TEXT NOT NULL DEFAULT '',
          primary_contact_phone TEXT NOT NULL DEFAULT '',
          primary_contact_email TEXT NOT NULL DEFAULT '',
          finance_contact TEXT NOT NULL DEFAULT '',
          operations_contact TEXT NOT NULL DEFAULT '',
          owner_id BIGINT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 5. Departments
    await client.query(`
      CREATE TABLE IF NOT EXISTS departments (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          department_name TEXT NOT NULL,
          department_code TEXT NOT NULL UNIQUE,
          company_id BIGINT,
          status TEXT NOT NULL DEFAULT 'Active',
          description TEXT NOT NULL DEFAULT '',
          owner_id BIGINT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 6. Designations
    await client.query(`
      CREATE TABLE IF NOT EXISTS designations (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          designation_name TEXT NOT NULL UNIQUE,
          designation_code TEXT NOT NULL UNIQUE,
          company_id BIGINT,
          department_id BIGINT,
          status TEXT NOT NULL DEFAULT 'Active',
          description TEXT NOT NULL DEFAULT '',
          owner_id BIGINT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 7. Org Roles
    await client.query(`
      CREATE TABLE IF NOT EXISTS org_roles (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          role_name TEXT NOT NULL UNIQUE,
          role_code TEXT NOT NULL UNIQUE,
          company_id BIGINT,
          department_id BIGINT,
          status TEXT NOT NULL DEFAULT 'Active',
          description TEXT NOT NULL DEFAULT '',
          owner_id BIGINT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 8. Employee Profiles
    await client.query(`
      CREATE TABLE IF NOT EXISTS employee_profiles (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          full_name TEXT NOT NULL,
          address TEXT NOT NULL DEFAULT '',
          birth_date TEXT NOT NULL DEFAULT '',
          joining_date TEXT NOT NULL DEFAULT '',
          user_id BIGINT UNIQUE,
          username TEXT NOT NULL DEFAULT '',
          phone TEXT NOT NULL DEFAULT '',
          email TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Active',
          father_name TEXT NOT NULL DEFAULT '',
          father_occupation TEXT NOT NULL DEFAULT '',
          mother_name TEXT NOT NULL DEFAULT '',
          mother_occupation TEXT NOT NULL DEFAULT '',
          current_address TEXT NOT NULL DEFAULT '',
          permanent_address TEXT NOT NULL DEFAULT '',
          mobile_number TEXT NOT NULL DEFAULT '',
          secondary_number TEXT NOT NULL DEFAULT '',
          emergency_number TEXT NOT NULL DEFAULT '',
          doc_aadhaar TEXT NOT NULL DEFAULT '',
          doc_pan TEXT NOT NULL DEFAULT '',
          doc_address_proof TEXT NOT NULL DEFAULT '',
          doc_light_bill TEXT NOT NULL DEFAULT '',
          owner_id BIGINT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 9. Branches
    await client.query(`
      CREATE TABLE IF NOT EXISTS branches (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          branch_name TEXT NOT NULL,
          company_id BIGINT,
          status TEXT NOT NULL DEFAULT 'Active',
          owner_id BIGINT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 10. Employees
    await client.query(`
      CREATE TABLE IF NOT EXISTS employees (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          employee_name TEXT NOT NULL,
          username TEXT NOT NULL UNIQUE,
          user_id BIGINT UNIQUE,
          profile_id BIGINT,
          company_id BIGINT NOT NULL,
          branch_id BIGINT NOT NULL,
          department_id BIGINT NOT NULL,
          designation_id BIGINT NOT NULL,
          org_role_id BIGINT NOT NULL,
          access_role_id TEXT NOT NULL,
          access_modules TEXT NOT NULL DEFAULT '',
          permission_flags TEXT NOT NULL DEFAULT '',
          reporting_authority_id BIGINT,
          status TEXT NOT NULL DEFAULT 'Active',
          shift_type TEXT NOT NULL DEFAULT 'General',
          base_salary NUMERIC(10,2) NOT NULL DEFAULT 0,
          owner_id BIGINT,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 11. Attendance Days
    await client.query(`
      CREATE TABLE IF NOT EXISTS attendance_days (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          employee_id BIGINT NOT NULL,
          user_id BIGINT NOT NULL,
          work_date DATE NOT NULL,
          check_in TIMESTAMPTZ,
          check_out TIMESTAMPTZ,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          UNIQUE (employee_id, work_date)
      )
    `);

    // 12. Payroll Slips
    await client.query(`
      CREATE TABLE IF NOT EXISTS payroll_slips (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          employee_id BIGINT NOT NULL,
          user_id BIGINT NOT NULL,
          month INTEGER NOT NULL,
          year INTEGER NOT NULL,
          total_days INTEGER NOT NULL,
          present_days INTEGER NOT NULL,
          leave_days INTEGER NOT NULL,
          absent_days INTEGER NOT NULL,
          base_salary NUMERIC(10,2) NOT NULL,
          basic_salary NUMERIC(10,2) NOT NULL,
          hra NUMERIC(10,2) NOT NULL,
          da NUMERIC(10,2) NOT NULL,
          gross_salary NUMERIC(10,2) NOT NULL,
          deductions NUMERIC(10,2) NOT NULL,
          net_salary NUMERIC(10,2) NOT NULL,
          status TEXT NOT NULL DEFAULT 'Draft',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          UNIQUE (employee_id, month, year)
      )
    `);

    // 13. Leave Requests
    await client.query(`
      CREATE TABLE IF NOT EXISTS leave_requests (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          employee_id BIGINT NOT NULL,
          user_id BIGINT NOT NULL,
          approver_employee_id BIGINT,
          leave_type TEXT NOT NULL,
          start_date DATE NOT NULL,
          end_date DATE NOT NULL,
          reason TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Pending',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 14. Notifications
    await client.query(`
      CREATE TABLE IF NOT EXISTS notifications (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          user_id BIGINT NOT NULL,
          title TEXT NOT NULL,
          body TEXT NOT NULL DEFAULT '',
          link TEXT NOT NULL DEFAULT '',
          is_read INTEGER NOT NULL DEFAULT 0,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 15. Leads
    await client.query(`
      CREATE TABLE IF NOT EXISTS leads (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          lead_name TEXT NOT NULL,
          company TEXT NOT NULL,
          source TEXT NOT NULL DEFAULT 'Website',
          assigned_to BIGINT,
          status TEXT NOT NULL DEFAULT 'New',
          created_on TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 16. Contacts
    await client.query(`
      CREATE TABLE IF NOT EXISTS contacts (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          full_name TEXT NOT NULL,
          company TEXT NOT NULL,
          designation TEXT NOT NULL DEFAULT '',
          email TEXT NOT NULL DEFAULT '',
          phone TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 17. Customers
    await client.query(`
      CREATE TABLE IF NOT EXISTS customers (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          customer_name TEXT NOT NULL,
          customer_group TEXT NOT NULL DEFAULT 'Corporate',
          city TEXT NOT NULL DEFAULT '',
          state TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 18. Opportunities
    await client.query(`
      CREATE TABLE IF NOT EXISTS opportunities (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          opportunity_name TEXT NOT NULL,
          account_id BIGINT,
          stage TEXT NOT NULL DEFAULT 'Qualification',
          expected_value NUMERIC(15,2) NOT NULL DEFAULT 0,
          expected_close DATE,
          probability INTEGER NOT NULL DEFAULT 10,
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 19. Quotations
    await client.query(`
      CREATE TABLE IF NOT EXISTS quotations (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          qtn_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          customer_id BIGINT,
          subject TEXT NOT NULL DEFAULT '',
          amount NUMERIC(15,2) NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Draft',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 20. BOQ / Solution Builder
    await client.query(`
      CREATE TABLE IF NOT EXISTS boq_solutions (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          boq_no TEXT NOT NULL UNIQUE,
          project_opportunity_id BIGINT,
          customer_id BIGINT,
          type TEXT NOT NULL DEFAULT 'New Installation',
          total_amount NUMERIC(15,2) NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Draft',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 21. Sales Orders
    await client.query(`
      CREATE TABLE IF NOT EXISTS sales_orders (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          sales_order_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          customer_id BIGINT,
          reference_quotation_id BIGINT,
          amount NUMERIC(15,2) NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Draft',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
          updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 22. Item Groups
    await client.query(`
      CREATE TABLE IF NOT EXISTS item_groups (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          group_name TEXT NOT NULL UNIQUE,
          parent_group TEXT NOT NULL DEFAULT '',
          no_of_items INTEGER NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 23. Brands
    await client.query(`
      CREATE TABLE IF NOT EXISTS brands (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          brand_name TEXT NOT NULL UNIQUE,
          country TEXT NOT NULL DEFAULT '',
          no_of_items INTEGER NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 24. UOMs
    await client.query(`
      CREATE TABLE IF NOT EXISTS uoms (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          uom_name TEXT NOT NULL UNIQUE,
          uom_type TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 25. Item Attributes
    await client.query(`
      CREATE TABLE IF NOT EXISTS item_attributes (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          attribute_name TEXT NOT NULL UNIQUE,
          type TEXT NOT NULL DEFAULT '',
          description TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 26. Price Lists
    await client.query(`
      CREATE TABLE IF NOT EXISTS price_lists (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          list_name TEXT NOT NULL UNIQUE,
          currency TEXT NOT NULL DEFAULT 'INR',
          applicable_to TEXT NOT NULL DEFAULT 'Customer',
          description TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 27. Tax Master
    await client.query(`
      CREATE TABLE IF NOT EXISTS taxes (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          tax_name TEXT NOT NULL UNIQUE,
          category TEXT NOT NULL DEFAULT '',
          description TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 28. Suppliers
    await client.query(`
      CREATE TABLE IF NOT EXISTS suppliers (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          supplier_name TEXT NOT NULL UNIQUE,
          code TEXT NOT NULL UNIQUE,
          contact_person TEXT NOT NULL DEFAULT '',
          phone TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 29. Items
    await client.query(`
      CREATE TABLE IF NOT EXISTS items (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          item_code TEXT NOT NULL UNIQUE,
          item_name TEXT NOT NULL,
          item_group TEXT NOT NULL DEFAULT '',
          brand TEXT NOT NULL DEFAULT '',
          uom TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    console.log("All tables created successfully!");
  } catch (error) {
    console.error("Error setting up database:", error);
  } finally {
    client.release();
  }
}

setupDatabase()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
