const { pool } = require('./db');

async function setupPurchaseDatabase() {
  const client = await pool.connect();
  try {
    console.log("Creating Purchase & Procurement tables...");

    // 1. Purchase RFQ
    await client.query(`
      CREATE TABLE IF NOT EXISTS purchase_rfq (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          rfq_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          supplier_id BIGINT,
          subject TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Active',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 2. Purchase Order
    await client.query(`
      CREATE TABLE IF NOT EXISTS purchase_order (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          po_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          supplier_id BIGINT,
          grand_total NUMERIC(15,2) NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Draft',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 3. Purchase GRN
    await client.query(`
      CREATE TABLE IF NOT EXISTS purchase_grn (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          grn_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          po_id BIGINT,
          warehouse TEXT NOT NULL DEFAULT '',
          received_by TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Completed',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 4. Purchase Invoice
    await client.query(`
      CREATE TABLE IF NOT EXISTS purchase_invoice (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          invoice_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          supplier_id BIGINT,
          amount NUMERIC(15,2) NOT NULL DEFAULT 0,
          status TEXT NOT NULL DEFAULT 'Unpaid',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 5. Purchase Payment
    await client.query(`
      CREATE TABLE IF NOT EXISTS purchase_payment (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          payment_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          supplier_id BIGINT,
          amount NUMERIC(15,2) NOT NULL DEFAULT 0,
          mode TEXT NOT NULL DEFAULT 'NEFT',
          status TEXT NOT NULL DEFAULT 'Paid',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    // 6. Purchase Return
    await client.query(`
      CREATE TABLE IF NOT EXISTS purchase_return (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          return_no TEXT NOT NULL UNIQUE,
          date DATE NOT NULL,
          supplier_id BIGINT,
          against_grn_id BIGINT,
          reason TEXT NOT NULL DEFAULT '',
          status TEXT NOT NULL DEFAULT 'Submitted',
          created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);

    console.log("Purchase & Procurement tables created successfully!");
  } catch (error) {
    console.error("Error setting up purchase database:", error);
  } finally {
    client.release();
  }
}

setupPurchaseDatabase()
  .then(() => process.exit(0))
  .catch((err) => {
    console.error(err);
    process.exit(1);
  });
