from __future__ import annotations

import uuid
from contextlib import contextmanager
from typing import Any, Iterator, Sequence

import psycopg
from psycopg.rows import dict_row

from core.auth import hash_password
from core.config import DATABASE_URL
from core.modules import get_function, get_module
from core.roles import MODULE_MIGRATE, ROLE_MIGRATE, defaults_for_role
from core.seed import SEED_RECORDS, SEED_USERS

OPEN_STATUSES = ("open", "draft", "unpaid", "in progress", "ordered", "active")


class Row(dict):
    def __getitem__(self, key: Any) -> Any:
        if isinstance(key, int):
            return list(self.values())[key]
        return super().__getitem__(key)


class Cursor:
    def __init__(self, cur: psycopg.Cursor, lastrowid: int | None = None):
        self._cur = cur
        self.lastrowid = lastrowid

    def fetchone(self) -> Row | None:
        row = self._cur.fetchone()
        return Row(row) if row is not None else None

    def fetchall(self) -> list[Row]:
        return [Row(row) for row in self._cur.fetchall()]


class Connection:
    def __init__(self, conn: psycopg.Connection):
        self._conn = conn

    def execute(self, sql: str, params: Sequence | None = None) -> Cursor:
        pg_sql = sql.replace("?", "%s")
        insert = pg_sql.lstrip().upper().startswith("INSERT") and "RETURNING" not in pg_sql.upper()
        if insert:
            pg_sql = pg_sql.rstrip().rstrip(";") + " RETURNING id"
        cur = self._conn.execute(pg_sql, params)
        lastrowid = None
        if insert:
            row = cur.fetchone()
            if row is not None:
                lastrowid = row["id"] if "id" in row else next(iter(row.values()))
        return Cursor(cur, lastrowid=lastrowid)

    def executemany(self, sql: str, params_seq: Sequence) -> None:
        with self._conn.cursor() as cur:
            cur.executemany(sql.replace("?", "%s"), list(params_seq))


def _connect() -> psycopg.Connection:
    if not DATABASE_URL:
        raise RuntimeError(
            "DATABASE_URL is not set. Copy webapp/.env.example to webapp/.env "
            "and point it at PostgreSQL (Render sets this automatically)."
        )
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


@contextmanager
def get_db() -> Iterator[Connection]:
    conn = _connect()
    try:
        yield Connection(conn)
        conn.commit()
    except Exception:
        conn.rollback()
        raise
    finally:
        conn.close()


def _replace_permissions(conn: Connection, user_id: int, perms: dict) -> None:
    conn.execute("DELETE FROM user_permissions WHERE user_id = ?", (user_id,))
    rows = [
        (user_id, mid, fid, 1 if read else 0, 1 if write else 0)
        for (mid, fid), (read, write) in perms.items()
        if read or write
    ]
    if rows:
        conn.executemany(
            """
            INSERT INTO user_permissions (user_id, module_id, function_id, can_read, can_write)
            VALUES (?, ?, ?, ?, ?)
            """,
            rows,
        )


def apply_role_defaults(user_id: int, role_id: str) -> None:
    with get_db() as conn:
        _replace_permissions(conn, user_id, defaults_for_role(role_id))


def init_db() -> None:
    with get_db() as conn:
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS records (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                module_id TEXT NOT NULL,
                entity TEXT NOT NULL,
                title TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'Open',
                notes TEXT NOT NULL DEFAULT '',
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                owner_id BIGINT,
                pipeline_id TEXT,
                source_id BIGINT,
                function_id TEXT
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS users (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username TEXT NOT NULL UNIQUE,
                full_name TEXT NOT NULL,
                role_id TEXT NOT NULL,
                password_hash TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                must_change_password INTEGER NOT NULL DEFAULT 0,
                is_active INTEGER NOT NULL DEFAULT 1
            )
            """
        )
        conn.execute(
            """
            CREATE TABLE IF NOT EXISTS user_permissions (
                user_id BIGINT NOT NULL,
                module_id TEXT NOT NULL,
                function_id TEXT NOT NULL,
                can_read INTEGER NOT NULL DEFAULT 0,
                can_write INTEGER NOT NULL DEFAULT 0,
                PRIMARY KEY (user_id, module_id, function_id)
            )
            """
        )

        for old, new in MODULE_MIGRATE.items():
            conn.execute("UPDATE records SET module_id = ? WHERE module_id = ?", (new, old))
        for old, new in ROLE_MIGRATE.items():
            conn.execute("UPDATE users SET role_id = ? WHERE role_id = ?", (new, old))

        for row in conn.execute("SELECT id, module_id, entity, function_id FROM records").fetchall():
            if row["function_id"] and get_function(row["module_id"], row["function_id"]):
                continue
            module = get_module(row["module_id"])
            if not module:
                continue
            match = next((fn for fn in module.functions if fn.title == row["entity"] or fn.id == row["entity"]), None)
            fn = match or module.functions[0]
            conn.execute(
                "UPDATE records SET function_id = ?, entity = ? WHERE id = ?",
                (fn.id, fn.title, row["id"]),
            )

        count = conn.execute("SELECT COUNT(*) FROM records").fetchone()[0]
        if count == 0:
            conn.executemany(
                """
                INSERT INTO records (module_id, function_id, entity, title, status, notes)
                VALUES (?, ?, ?, ?, ?, ?)
                """,
                SEED_RECORDS,
            )

        user_count = conn.execute("SELECT COUNT(*) FROM users").fetchone()[0]
        if user_count == 0:
            conn.executemany(
                """
                INSERT INTO users (username, full_name, role_id, password_hash, must_change_password, is_active)
                VALUES (?, ?, ?, ?, ?, 1)
                """,
                [
                    (username, full_name, role_id, hash_password(password), must_change)
                    for username, full_name, role_id, password, must_change in SEED_USERS
                ],
            )

        for user in conn.execute("SELECT id, role_id FROM users").fetchall():
            existing = conn.execute(
                "SELECT COUNT(*) FROM user_permissions WHERE user_id = ?",
                (user["id"],),
            ).fetchone()[0]
            if existing == 0:
                _replace_permissions(conn, user["id"], defaults_for_role(user["role_id"]))


def get_user_by_username(username: str) -> Row | None:
    with get_db() as conn:
        return conn.execute(
            "SELECT * FROM users WHERE lower(username) = lower(?)",
            (username.strip(),),
        ).fetchone()


def get_user_by_id(user_id: int) -> Row | None:
    with get_db() as conn:
        return conn.execute("SELECT * FROM users WHERE id = ?", (user_id,)).fetchone()


def list_users() -> list[Row]:
    with get_db() as conn:
        return conn.execute("SELECT * FROM users ORDER BY lower(full_name)").fetchall()


def get_user_permissions(user_id: int) -> dict[tuple[str, str], tuple[bool, bool]]:
    with get_db() as conn:
        rows = conn.execute(
            "SELECT module_id, function_id, can_read, can_write FROM user_permissions WHERE user_id = ?",
            (user_id,),
        ).fetchall()
    return {
        (row["module_id"], row["function_id"]): (bool(row["can_read"]), bool(row["can_write"]))
        for row in rows
    }


def save_user_permissions(user_id: int, perms: dict[tuple[str, str], tuple[bool, bool]]) -> None:
    with get_db() as conn:
        _replace_permissions(conn, user_id, perms)


def create_user(
    username: str,
    full_name: str,
    role_id: str,
    password: str,
    must_change_password: bool = True,
    is_active: bool = True,
) -> int:
    with get_db() as conn:
        cursor = conn.execute(
            """
            INSERT INTO users (
                username, full_name, role_id, password_hash, must_change_password, is_active
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            (
                username.strip().lower(),
                full_name.strip(),
                role_id,
                hash_password(password),
                1 if must_change_password else 0,
                1 if is_active else 0,
            ),
        )
        user_id = int(cursor.lastrowid)
        _replace_permissions(conn, user_id, defaults_for_role(role_id))
        return user_id


def update_user(
    user_id: int,
    full_name: str,
    role_id: str,
    is_active: bool,
    password: str | None = None,
    must_change_password: bool | None = None,
) -> None:
    with get_db() as conn:
        conn.execute(
            "UPDATE users SET full_name = ?, role_id = ?, is_active = ? WHERE id = ?",
            (full_name.strip(), role_id, 1 if is_active else 0, user_id),
        )
        if password:
            conn.execute(
                "UPDATE users SET password_hash = ? WHERE id = ?",
                (hash_password(password), user_id),
            )
        if must_change_password is not None:
            conn.execute(
                "UPDATE users SET must_change_password = ? WHERE id = ?",
                (1 if must_change_password else 0, user_id),
            )


def set_password(user_id: int, password: str, must_change_password: bool = False) -> None:
    with get_db() as conn:
        conn.execute(
            """
            UPDATE users
            SET password_hash = ?, must_change_password = ?
            WHERE id = ?
            """,
            (hash_password(password), 1 if must_change_password else 0, user_id),
        )


def list_records(module_id: str, query: str = "", function_id: str | None = None) -> list[Row]:
    sql = "SELECT * FROM records WHERE module_id = ?"
    params: list = [module_id]
    if function_id:
        sql += " AND function_id = ?"
        params.append(function_id)
    if query.strip():
        like = f"%{query.strip()}%"
        sql += " AND (title ILIKE ? OR entity ILIKE ? OR status ILIKE ? OR notes ILIKE ?)"
        params.extend([like, like, like, like])
    sql += " ORDER BY id DESC"
    with get_db() as conn:
        return conn.execute(sql, params).fetchall()


def get_record(record_id: int, module_id: str | None = None) -> Row | None:
    sql = "SELECT * FROM records WHERE id = ?"
    params: list = [record_id]
    if module_id:
        sql += " AND module_id = ?"
        params.append(module_id)
    with get_db() as conn:
        return conn.execute(sql, params).fetchone()


def save_record(
    module_id: str,
    entity: str,
    title: str,
    status: str,
    notes: str,
    record_id: int | None = None,
    owner_id: int | None = None,
    pipeline_id: str | None = None,
    source_id: int | None = None,
    function_id: str | None = None,
) -> int:
    title = title.strip()
    status = status.strip() or "Open"
    notes = notes.strip()
    with get_db() as conn:
        if record_id is None:
            cursor = conn.execute(
                """
                INSERT INTO records (
                    module_id, function_id, entity, title, status, notes,
                    owner_id, pipeline_id, source_id
                )
                VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    module_id,
                    function_id,
                    entity,
                    title,
                    status,
                    notes,
                    owner_id,
                    pipeline_id,
                    source_id,
                ),
            )
            return int(cursor.lastrowid)
        conn.execute(
            """
            UPDATE records
            SET function_id = ?, entity = ?, title = ?, status = ?, notes = ?
            WHERE id = ? AND module_id = ?
            """,
            (function_id, entity, title, status, notes, record_id, module_id),
        )
        return record_id


def delete_record(record_id: int, module_id: str) -> None:
    with get_db() as conn:
        conn.execute(
            "DELETE FROM records WHERE id = ? AND module_id = ?",
            (record_id, module_id),
        )


def counts_by_module(module_ids: list[str] | None = None) -> dict[str, int]:
    sql = "SELECT module_id, COUNT(*) AS c FROM records"
    params: list[str] = []
    if module_ids:
        placeholders = ", ".join("?" for _ in module_ids)
        sql += f" WHERE module_id IN ({placeholders})"
        params.extend(module_ids)
    sql += " GROUP BY module_id"
    with get_db() as conn:
        rows = conn.execute(sql, params).fetchall()
    return {row["module_id"]: row["c"] for row in rows}


def dashboard_stats(module_ids: list[str] | None = None) -> dict:
    placeholders_open = ", ".join("?" for _ in OPEN_STATUSES)
    where = ""
    params: list = []
    if module_ids:
        module_ph = ", ".join("?" for _ in module_ids)
        where = f" WHERE module_id IN ({module_ph})"
        params.extend(module_ids)
    with get_db() as conn:
        total = conn.execute(f"SELECT COUNT(*) FROM records{where}", params).fetchone()[0]
        open_params = list(OPEN_STATUSES) + params
        open_where = f" WHERE lower(status) IN ({placeholders_open})"
        if module_ids:
            module_ph = ", ".join("?" for _ in module_ids)
            open_where += f" AND module_id IN ({module_ph})"
        open_count = conn.execute(
            f"SELECT COUNT(*) FROM records{open_where}",
            open_params,
        ).fetchone()[0]
        recent = conn.execute(
            f"""
            SELECT id, module_id, function_id, entity, title, status, created_at, pipeline_id
            FROM records{where} ORDER BY id DESC LIMIT 6
            """,
            params,
        ).fetchall()
    return {"total": total, "open": open_count, "recent": recent}


def list_pipeline(pipeline_id: str) -> list[Row]:
    with get_db() as conn:
        return conn.execute(
            """
            SELECT * FROM records
            WHERE pipeline_id = ?
            ORDER BY id ASC
            """,
            (pipeline_id,),
        ).fetchall()


def new_pipeline_id() -> str:
    return uuid.uuid4().hex[:12]


def set_pipeline_id(record_id: int, pipeline_id: str) -> None:
    with get_db() as conn:
        conn.execute(
            "UPDATE records SET pipeline_id = ? WHERE id = ?",
            (pipeline_id, record_id),
        )


def set_record_status(record_id: int, status: str) -> None:
    with get_db() as conn:
        conn.execute(
            "UPDATE records SET status = ? WHERE id = ?",
            (status, record_id),
        )


def function_record_counts(module_id: str) -> dict[str, int]:
    with get_db() as conn:
        rows = conn.execute(
            """
            SELECT function_id, COUNT(*) AS c FROM records
            WHERE module_id = ?
            GROUP BY function_id
            """,
            (module_id,),
        ).fetchall()
    return {row["function_id"]: row["c"] for row in rows if row["function_id"]}


def ping_db() -> bool:
    with get_db() as conn:
        conn.execute("SELECT 1")
    return True
